name: Trigger Fork Repo Action
on:
  push:
    branches:
      - master
jobs:
  trigger-fork:
    if: github.repository_owner == "subject-test-26"
    runs-on: ubuntu-latest
    steps:
      - run: echo "main branch pushed"
