name: Trigger Sync

on:
  repository_dispatch:
    types: [main_updated]

jobs:
  trigger-sync:
    if: github.repository == 'yulrang/ci-cd-copied'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'sync'